### ISSUE TITLE
Generating empty raster IC

### ISSUE THREAD

**Issue by hafez-ahmad** [HydrogeomorphologyTools/Sediment-Connectivity-and-Surface-Roughness-python-scripts#1]
I am trying to run it for same projected DTM, shapefile , everything looks okay but it is creating empty IC raster. Would you please check it what is going on?

**Comment by HydrogeomorphologyTools** [comment]
Hello, did you try using SedInConnect stand-alone? Is it providing the same errors?
If no details on the issue are available, could you post (or send) a sample file (preferably small) with DTM, shapefile, and, if needed , also W for a test?
